-- MySQL Script generated by MySQL Workbench
-- 09/02/15 15:11:16
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `phoneNumber` INT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userID`));


-- -----------------------------------------------------
-- Table `mydb`.`PropertyListing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PropertyListing` (
  `propertyID` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `price` DECIMAL(2) NULL,
  `numBathroom` INT NULL,
  `numBedroom` INT NULL,
  `numCarPorts` INT NULL,
  `userID` INT NOT NULL,
  `imageID` INT NULL,
  PRIMARY KEY (`propertyID`),
  INDEX `userID_idx` (`userID` ASC),
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `mydb`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gallery` (
  `ImageID` INT NOT NULL AUTO_INCREMENT,
  `Images` VARCHAR(255) NOT NULL,
  `PropertyID` INT NULL,
  PRIMARY KEY (`ImageID`),
  INDEX `PropertyID_idx` (`PropertyID` ASC),
  CONSTRAINT `PropertyID`
    FOREIGN KEY (`PropertyID`)
    REFERENCES `mydb`.`PropertyListing` (`propertyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
